spring:
  application:
    name: volunteer-gateway-service
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
  security:
    oauth2:
      client:
        registration:
          yandex:
            provider: yandex
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
            redirect-uri: ${BASE_URL}/login/oauth2/code/yandex
            authorization-grant-type: authorization_code
            client-name: Yandex
        provider:
          yandex:
            authorization-uri: https://oauth.yandex.ru/authorize
            token-uri: https://oauth.yandex.ru/token
            user-info-uri: https://login.yandex.ru/info
            user-name-attribute: default_email
